### ISSUE TITLE
Asynchronous containers

### ISSUE THREAD

**Issue by jpbruinsslot** [erroneousboat/docker-django#1]
Because docker compose asynchronously starts the containers, it will happen that the db container isn't ready to accept connections when the app container wants to connect to it. This is [reported](https://registry.hub.docker.com/_/postgres/) as a caveat at the official postgres image repo.

At the moment I solved this by using scripts that will check whether the db container is ready to accept connection. However I'd like to use a more elegant solution.

So with the creation of this issue I want to investigate if this is possible and what I can use.

**Comment by jpbruinsslot** [comment]
Issue that is being addressed with no definitive solution, see:
http://stackoverflow.com/a/27678206
http://stackoverflow.com/a/21194386

**Comment by omarabid** [comment]
No official response for this?

**Comment by jpbruinsslot** [comment]
@omarabid No, unfortunately the docker compose issue concerning this remains open, and the most favourable solution seems to be to create a script that checks whether a container is 'ready'
