### ISSUE TITLE
Nginx and Django logging

### ISSUE THREAD

**Issue by SamuelM333** [erroneousboat/docker-django#12]
Great template. I have been using it and it works great. How can I set up logging after it is running as a background process?

**Comment by jpbruinsslot** [comment]
Thanks! You can use the docker-compose to view the logs, e.g:

```bash
$ docker-compose logs -f webapp
$ docker-compose logs -f webserver
```

Source: https://docs.docker.com/compose/reference/logs/

**Comment by SamuelM333** [comment]
Oh thanks. You should add that on the readme. Also, I was having some issues with nginx not redirecting from http to https.

**Comment by SamuelM333** [comment]
Hey, that fix for the http redirecting didn't work. From the logs I see that if I request to http I'll get a 301 but no 200 after that. So looks like it is returning the 301 for redirecting but it isn't actually doing it.

**Comment by jpbruinsslot** [comment]
Could you try and open it in browser with "incognito mode" enabled, it seems to be a caching issue with browsers. You can also try to check if it works by using `curl http://localhost`.

**Comment by SamuelM333** [comment]
Actually I'm using postman for the testing, so same as curl.

**Comment by SamuelM333** [comment]
With curl I get:

```
$ curl http://localhost
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
````
