### ISSUE TITLE
Nginx conf + envsubst issue

### ISSUE THREAD

**Issue by tosborne1215** [erroneousboat/docker-django#13]
start.sh uses envsubst to replace environment variables in the nginx conf, but the nginx conf also contains variables that are not environment variables that are prefaced with a $ which means they get replaced with nothing. Specifically in the nginx.tmpl you are using this variable: $request_uri. When I get redirected from http to https I do not have my path preserved.

This could work. By passing the variables it will not stomp on all the variables in nginx.tmpl
`envsubst $(compgen -v | grep NGINX* | sed 's/NGINX/$NGINX/' | tr "\n" ",") < nginx.tmpl > /etc/nginx/nginx.conf`

**Comment by MBARIMike** [comment]
@erroneousboat Your project really helped me Dockerize my project. I made a fix to deal with the $request_uri not surviving template processing. I submitted https://github.com/erroneousboat/docker-django/pull/17 and https://github.com/erroneousboat/docker-django/pull/18 that will fix this issue. Thanks again for sharing this with us.

**Comment by jpbruinsslot** [comment]
I've used your suggestions and implemented it.
