### ISSUE TITLE
Nginx server can't connect with webapp container

### ISSUE THREAD

**Issue by rumski20** [erroneousboat/docker-django#14]
I'm trying to use this setup with an existing django project. I've mounted my code as a volume in the webapp directory at `<local_dir>:/srv/<project_name>`.

When I run `docker-compose up -d` I get the following error straight away in the logs:
```
webserver_1  | 2017/09/26 15:13:35 [emerg] 8#8: host not found in upstream "webapp:8000" in /etc/nginx/nginx.conf:19
webserver_1  | nginx: [emerg] host not found in upstream "webapp:8000" in /etc/nginx/nginx.conf:19
```
And then both the webapp and webserver containers exit without reporting anything further in the logs.

Any ideas how to improve the logging for the purposes of debugging, or what might be happening here?

**Comment by jpbruinsslot** [comment]
I'll have a look over the weekend to see what was is happening

**Comment by bartkim0426** [comment]
same issue here too..

**Comment by bartkim0426** [comment]
I recognized that I didn't have static-files dir in root dir, so I deleted static-files volumes in webserver, and webapp. then that error gone. I wish it helps

**Comment by jpbruinsslot** [comment]
This could be that the webapp, and/or db containers are not yet running. You can solve it by individually starting the containers.
