### ISSUE TITLE
Question about docker files

### ISSUE THREAD

**Issue by vinPopulaire** [erroneousboat/docker-django#15]
Since I recently started working with docker, what is the purpose of having both
```
ADD ./starter /srv/starter
```
in the Dockerfile and
```
volumes:
- ./webapp/starter:/srv/starter
```
in the docker-compose?

**Comment by jpbruinsslot** [comment]
Mainly when eventually you stop developing you'd want to stop adding the volume to your docker container. Then you want to have the webapp code added to your container.
