### ISSUE TITLE
Error handling in DB check loop

### ISSUE THREAD

**Issue by asfaltboy** [erroneousboat/docker-django#16]
Do we really need this `set -e` call? I'm not sure on what systems the bash script will continue to the line 10, but for me, [as per bash documentation][1], the script exits if first test (L10) exists with code 1.

https://github.com/erroneousboat/docker-django/blob/4b9ee750776933c690e18074ce02981b88057290/webapp/config/start.sh#L9-L15

Instead, I think we can keep using `set -e` and simplify the script with something like:

```bash
set -e
until python3 ./database_check.py; do
    sleep 5; echo "*** Waiting for postgres container ..."
done
echo "*** Postgres container available..."
set +e
```

[1]: http://www.gnu.org/software/bash/manual/bashref.html#The-Set-Builtin

**Comment by jpbruinsslot** [comment]
Thank you for your suggestion, and I've implemented it.
